BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "temp_log" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`sensor`	TEXT,
	`temp`	REAL NOT NULL,
	`datetime`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `status_log` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`status`	INTEGER NOT NULL,
	`fan`	INTEGER NOT NULL,
	`datetime`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `schedule` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`dow`	INTEGER,
	`temp`	REAL,
	`time`	INTEGER
);
CREATE TABLE IF NOT EXISTS `config` (
	`key`	TEXT NOT NULL UNIQUE,
	`value`	TEXT,
	PRIMARY KEY(key)
);
COMMIT;
